### ISSUE TITLE
why do you use RabbitMQ

### ISSUE THREAD

**Issue by MaryLilian** [mallgroup/rabbitmq#28]
Hi, I am reading your project and I love this project
I have a question, why do you choose RabbitMQ in your project instead of others like ZeroMQ or Kafka, are there any special features but others dont have it. Can you share me  it. I am wondering when I should choose RabbitMQ instead of others like ZeroMQ or Kafka

**Comment by bckp** [comment]
Our company use RabbitMQ in lot projects, so it is logical to use it... we use rabbit on separate clusters and they communicate with each other thru federations, so it does what we need...
